### ISSUE TITLE
[RFE] Option to render the whole STIG in one single page

### ISSUE THREAD

**Issue by ggbecker** [Mab879/stig-a-view#3]
So I can easily search the whole document at once.

**Comment by Mab879** [comment]
I have made a quick draft of this feature. It has been deployed to the [staging server](https://stage.stigaview.com/products/rhel7/v3r8/?onepage). Let me know what you think.

**Comment by ggbecker** [comment]
looks good. The last row has a redundant separator.

I think the STIG ids can also be a link to the single item page

**Comment by Mab879** [comment]
I have incorporated those changes. Those changes should landing in production within next couple of days.

**Comment by ggbecker** [comment]
This can probably be closed.

**Comment by Mab879** [comment]
Thanks for the idea, it's in production now.

Merged in a605eb9f33e073ae2a671b6209453b6ee140db5f
